module.exports = class Configuration {
    id
    e_nombre
    e_nombre_legal
    e_domicilio
    e_localidad
    e_codpostal
    e_provincia
    e_cuit
    e_brutos
    e_actividades
    e_telefono
    e_responsable
    e_email
    e_web
    e_numero_cliente
    e_cons_final
    e_numero_legajo
    e_numero_agenda
    e_numero_proveedor
    e_numero_producto
    e_numero_caja
    e_numero_fc
    e_numero_nc
    e_numero_cb
    e_punto_venta
    e_numero_fc_dgi
    e_numero_nc_dgi
    e_numero_cb_dgi
    e_importante
    e_cotiz_dolar
    e_logo
    e_bases
    e_destino
    e_vencimiento
    e_cliente
    e_path
    e_certificado
    e_claveprivada
    e_servidor
    e_homologacion_wsaa
    e_homologacion
    e_produccion_wsaa
    e_produccion
    e_token
    e_sign
    e_fecha_ticket
    e_producto
    e_mes_inicio
    e_cant_meses
    e_dto_mes
    e_dto_ultimo_mes
    e_sucursal
    e_sucursal_nombre
    e_nombre_sistema
    e_smtp
    e_user
    e_pasword
    e_port
    e_seg
    e_recargo_adm
    e_recargo_porc
    e_recargo
    e_factura
}